### ISSUE TITLE
separar gulp tasks

### ISSUE THREAD

**Issue by darlanmendonca** [abc-dev/2016#18]
notei algumas tasks em um mesmo arquivo (./tasks/copy.js por exemplo).

o ideal é termos uma task apenas por arquivo

pretendo dar uma olhada em algum módulo existente / ou fazer um, pra validar tais coisas do gulp

alguém conhece um eslint plugin da hora q cubra estas necessidads?

**Comment by woliveiras** [comment]
Pra coisas como separação de tasks em módulos eu nunca vi ein mano. :confused:

Seria bem louco se criasse algo assim! :raised_hands:

**Comment by darlanmendonca** [comment]
:D, já aplicado
