### ISSUE TITLE
lint de scripts

### ISSUE THREAD

**Issue by darlanmendonca** [abc-dev/2016#3]
galera, qual os patterns pra seguir?

n encontrei o o .jshintrc, ou nenhuma definição

outra coisa, sugiro mto o eslint, pelo mesmo ser mais flexível, por exemplo, da pra add patterns do angular

q axam? @woliveiras @akfzambrana @ubirajarapelli

**Comment by akfzambrana** [comment]
eu me abstenho de comentar pois não conheço muito sobre o assunto, deixo vcs decidirem

**Comment by woliveiras** [comment]
Acho que nem precisa esquentar com isso mano.

Visto que é um site institucional, o máximo que vai rolar é um Module Pattern pra englobar algum plugin jQuery, por exemplo, mas acho que seria até esquentar a toa com algo que não tem objetivo de ser escalável.

Tipo, só de seguir as boas práticas de JS, já é sucesso! 

Bota o bicho pra pegar as cagadas de JS que já vai ajudar bagarai. 🙌

**Comment by woliveiras** [comment]
Daria pra tacar pau numa primeira versão do JS e, se precisar mesmo, a gente vê algum esquema pra padronizar bonito. Que tal?

**Comment by darlanmendonca** [comment]
então, por isso q é bom um lint, ele define um padrão, mesmo quem n manja,se for mexer, o lint apita, e mostra oq sta diferentão

**Comment by darlanmendonca** [comment]
o ruim é qo o jshint n cobre mta coisa :(

ja o eslint, cobre mais coisas

**Comment by woliveiras** [comment]
Hmmmm

Verdade mano.

Pow, é uma boa colocar, mas quais padrões adotaríamos?

**Comment by darlanmendonca** [comment]
um simples => https://github.com/felixge/node-style-guide

**Comment by darlanmendonca** [comment]
https://github.com/felixge/node-style-guide/blob/master/.jshintrc

**Comment by darlanmendonca** [comment]
embora eu costumo usar tdas estas regras em eslint

``` js
{
    semi: [required, 'always'],
    'comma-dangle': [required, 'always-multiline'],
    'comma-style': [required, 'last'],
    indent: [required, 2],
    curly: [required, 'all'],
    'brace-style': [required, '1tbs'],
    quotes: [required, 'single'],
    'object-curly-spacing': [required, 'never'],
    'array-bracket-spacing': [required, 'never'],
    'space-infix-ops': [required, {int32Hint: false}],
    'no-var': required,
    strict: required,
    'no-undef': required,
    'no-unused-vars': [required, {vars: 'all', args: 'after-used'}],
    'block-scoped-var': required,
    camelcase: required,
    'eol-last': required,
    eqeqeq: [required, 'smart'],
    'max-depth': [optional, 3],
    'max-len': [optional, 120],
    'max-statements': [optional, 15],
    'new-cap': optional,
    'no-extend-native': required,
    'no-mixed-spaces-and-tabs': required,
    'no-trailing-spaces': required,
    'no-multiple-empty-lines': [required, {max: 1, maxBOF: 0}],
    'block-spacing': [required, 'never'],
    'newline-per-chained-call': required,
    'keyword-spacing': required,
    'key-spacing': [required, {afterColon: true}],
    'space-unary-ops': required,
  }
```

**Comment by darlanmendonca** [comment]
os links pra kda rule q mencionei acima

http://eslint.org/docs/rules/semi
http://eslint.org/docs/rules/comma-dangle
http://eslint.org/docs/rules/comma-style
http://eslint.org/docs/rules/indent
http://eslint.org/docs/rules/curly
http://eslint.org/docs/rules/brace-style
http://eslint.org/docs/rules/quotes
http://eslint.org/docs/rules/object-curly-spacing
http://eslint.org/docs/rules/array-bracket-spacing
http://eslint.org/docs/rules/space-infix-ops
http://eslint.org/docs/rules/no-var
http://eslint.org/docs/rules/strict
http://eslint.org/docs/rules/no-undef
http://eslint.org/docs/rules/no-unused-vars
http://eslint.org/docs/rules/block-scoped-var
http://eslint.org/docs/rules/camelcase
http://eslint.org/docs/rules/eol-last
http://eslint.org/docs/rules/eqeqeq
http://eslint.org/docs/rules/max-depth
http://eslint.org/docs/rules/max-len
http://eslint.org/docs/rules/max-statements
http://eslint.org/docs/rules/new-cap
http://eslint.org/docs/rules/no-extend-native
http://eslint.org/docs/rules/no-mixed-spaces-and-tabs
http://eslint.org/docs/rules/no-trailing-spaces
http://eslint.org/docs/rules/no-multiple-empty-lines
http://eslint.org/docs/rules/block-spacing
http://eslint.org/docs/rules/newline-per-chained-call
http://eslint.org/docs/rules/keyword-spacing
http://eslint.org/docs/rules/key-spacing
http://eslint.org/docs/rules/space-unary-ops

**Comment by darlanmendonca** [comment]
dai eu costumo fazer o seguinte, tem tarefa d lint, rodando antes d concatenar os scripts

se der um error no lint, n procede c as tarefas d scripts, ou seja, n é gerado arquivo js concatenado, mto menos browser recarrrega, etc

forcando a seguir o pattern :D

n é necessário decorar nenhuma das regras, se vc codar algo q fere o pattern, aparece o erro no terminal, informando o nome da regra quebrada, ao googlar eslint NOME DA REGRA, vc axa a documentacao e entende oq é a regra, dawe é mamata ir seguindo codigo padronizado

**Comment by darlanmendonca** [comment]
eslint tbm é mais completo, da pra plugar nele, patterns specificos a um framework por exemplo.

tipo, patterns do angular, patterns do react, patterns do seu projeto da empresa :D

mto top, usei jshint por um bom tmpo, mas o eslint é mto flexível, é fantástico

**Comment by darlanmendonca** [comment]
ja qto as regras a seguir, podemos mudar dpois tbm, whatever, oq importa, é q tenha um lint c algumas rules, e sigamos, isto facilita mto o projeto pra tds codarem

**Comment by woliveiras** [comment]
@darlanmendonca, não consegui um tempinho pra olhar melhor isso, mas já colaboro mais aqui.

Creio que você poderia subir com as configurações que você acha primordial primeiro e mudamos caso necessário. Nop 😄

**Comment by darlanmendonca** [comment]
yep, blz, vou fazer um pull request, se no decorrer do projeto algum rule n for aceita, a gnte tira a msma ou altera, rs

**Comment by darlanmendonca** [comment]
https://github.com/abc-dev/2016/pull/5 look please

**Comment by woliveiras** [comment]
Show de bola, qualquer coisa a gente reabre a issue. 😄
